eigth = ["abet", "accord", "adept", "advocate", "agile", "allot", "aloof", "amiss", "analogy", "anarchy", "antics", "apprehend", "ardent", "articulate", "assail", "assimilate", "atrocity", "attribute", "audacious", "augment", "authority", "avail", "avid", "awry", "balmy", "banter", "barter", "benign", "bizarre", "blasé", "bonanza", "bountiful", "cache", "capacious", "caption", "chastise", "citadel", "cite", "clad", "clarify", "commemorate", "component", "concept", "confiscate", "connoisseur", "conscientious", "conservative", "contagious", "conventional", "convey", "crucial", "crusade", "culminate", "deceptive", "decipher", "decree", "deface", "defect", "deplore", "deploy", "desist", "desolate", "deter", "dialect", "dire", "discern", "disdain", "disgruntled", "dispatch", "disposition", "doctrine", "dub", "durable", "eccentric", "elite", "embargo", "embark", "encroach", "endeavor", "enhance", "enigma", "epoch", "era", "eventful", "evolve", "exceptional", "excerpt", "excruciating", "exemplify", "exotic", "facilitate", "fallacy", "fastidious", "feasible", "fend", "ferret", "flair", "flustered", "foreboding", "forfeit", "formidable", "fortify", "foster", "gaunt", "gingerly", "glut", "grapple", "grope", "gullible", "haggard", "haven", "heritage", "hindrance", "hover", "humane", "imperative", "inaugurate", "incense", "indifferent", "infinite", "instill", "institute", "intervene", "intricate", "inventive", "inventory", "irascible", "jurisdiction", "languish", "legendary", "liberal", "loll", "lucrative", "luminous", "memoir", "mercenary", "mien", "millennium", "minimize", "modify", "muse", "muster", "onslaught", "ornate", "ovation", "overt", "pang", "panorama", "perspective", "phenomenon", "pioneer", "pithy", "pivotal", "plausible", "plunder", "porous", "preposterous", "principal", "prodigy", "proficient", "profound", "pseudonym", "pungent", "rankle", "rational", "rebuke", "reception", "recourse", "recur", "renounce", "renown", "revenue", "rubble", "rue", "sage", "sedative", "serene", "servile", "shackle", "sleek", "spontaneous", "sporadic", "stamina", "stance", "staple", "stint", "strident", "sublime", "subside", "succumb", "surpass", "susceptible", "swelter", "tedious", "teem", "theme", "tirade", "tract", "transition", "trepidation", "turbulent", "tycoon", "ultimate", "ungainly", "vie", "vilify", "voracious", "wage", "wrangle"]

eigth.shuffle.take(100).sort.each_slice(20).to_a.each do |group|
	group.each do |word|
		puts word
	end
	puts
end

_.flatten
p _

eigth_hsb_2 = ["advocate", "agile", "allot", "aloof", "analogy", "anarchy", "apprehend", "atrocity", "augment", "avid", "awry", "banter", "barter", "bizarre", "bonanza", "cache", "capacious", "chastise", "cite", "clad", "clarify", "commemorate", "component", "concept", "confiscate", "connoisseur", "crucial", "culminate", "decipher", "decree", "deface", "deploy", "desolate", "dialect", "dire", "disposition", "eccentric", "embargo", "enigma", "eventful", "evolve", "excerpt", "exotic", "facilitate", "fastidious", "feasible", "ferret", "foreboding", "foster", "gingerly", "grapple", "grope", "gullible", "haggard", "heritage", "humane", "imperative", "infinite", "intervene", "intricate", "inventive", "irascible", "jurisdiction", "loll", "memoir", "millennium", "muster", "onslaught", "ornate", "ovation", "overt", "pang", "perspective", "plausible", "porous", "preposterous", "principal", "pseudonym", "rational", "reception", "recourse", "recur", "renown", "sleek", "staple", "strident", "sublime", "subside", "succumb", "swelter", "tract", "transition", "trepidation", "turbulent", "tycoon", "ultimate", "ungainly", "vie", "vilify", "voracious"]
